captured: '2025-12-10T18:46:43.145877Z'
files:
- path: config.yaml
  sha256: 1881d45f2be853198f3b9019652d52f8c4b54f5454c6200210ece27afed557fb
  size: 245
- path: constraints.yaml
  sha256: 69765410309328b5f803222bfa627cccdf15556757a953ea95764ee191492357
  size: 483
